# backend/configs/config.yaml

loadBalancerPort: 8080
apiPort: 8081
apiKey: "dev_api_key_123"
loadBalancingAlgorithm: "roundrobin"
sslCertPath: "./backend/certs/cert.pem"
sslKeyPath: "./backend/certs/key.pem"

backendServers: []  # Start with empty list - add servers via UI/API

healthCheck:
  intervalSeconds: 5
  timeoutSeconds: 3
  path: "/"
