loadBalancerPort: 8080
apiPort: 8081
backendServers:
  - id: "server1"
    url: "http://localhost:9001"
    weight: 1
  - id: "server2"
    url: "http://localhost:9002"
    weight: 1
healthCheck:
  intervalSeconds: 5
  timeoutSeconds: 3
  path: "/health"
